# Generated by Django 6.0.4 on 2026-04-26 15:41

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата занятия')),
                ('comment', models.TextField(verbose_name='Что делал на занятии')),
                ('file_name', models.CharField(blank=True, max_length=255, verbose_name='Имя файла')),
                ('file_url', models.URLField(blank=True, max_length=2048, verbose_name='Ссылка (Я.Диск)')),
                ('grade', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Оценка')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('graded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_entries', to=settings.AUTH_USER_MODEL, verbose_name='Выставил оценку')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to=settings.AUTH_USER_MODEL, verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Запись о занятии',
                'verbose_name_plural': 'Записи о занятиях',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
